import * as Modules from '../utils/modules';

const React = Modules.common.React;
const ComponentsModule = Modules.common.Components.General;
const FormsModule = Modules.common.Components.Forms;

const {
  lazy,
  memo,
  useCallback,
  useContext,
  useEffect,
  useImperativeHandle,
  useMemo,
  useReducer,
  useRef,
  useState,
} = React;

const {
  Alert,

  Button,
  FlatList,
  Image,
  ImageBackground,
  KeyboardAvoidingView,
  Modal,
  Pressable,
  RefreshControl,
  ScrollView,
  SectionList,
  StatusBar,
  StyleSheet,
  Switch,
  Text,
  TextInput,
  TouchableHighlight,
  TouchableOpacity,
  TouchableWithoutFeedback,
  Touchable,
  View,
  VirtualizedList,
} = ComponentsModule;

const {
  Form,
  FormArrow,
  FormCTA,
  FormCTAButton,
  FormCardSection,
  FormCheckbox,
  FormDivider,
  FormHint,
  FormIcon,
  FormInput,
  FormLabel,
  FormRadio,
  FormRow,
  FormSection,
  FormSelect,
  FormSubLabel,
  FormSwitch,
  FormTernaryCheckBox,
  FormText,
  FormTextColors,
  FormTextSizes,
} = FormsModule;

export {
  React,
  lazy,
  memo,
  useCallback,
  useContext,
  useEffect,
  useImperativeHandle,
  useMemo,
  useReducer,
  useRef,
  useState,

  Alert,
  Button,
  FlatList,
  Image,
  ImageBackground,
  KeyboardAvoidingView,
  Modal,
  Pressable,
  RefreshControl,
  ScrollView,
  SectionList,
  StatusBar,
  StyleSheet,
  Switch,
  Text,
  TextInput,
  TouchableHighlight,
  TouchableOpacity,
  TouchableWithoutFeedback,
  Touchable,
  View,
  VirtualizedList,

  Form,
  FormArrow,
  FormCTA,
  FormCTAButton,
  FormCardSection,
  FormCheckbox,
  FormDivider,
  FormHint,
  FormIcon,
  FormInput,
  FormLabel,
  FormRadio,
  FormRow,
  FormSection,
  FormSelect,
  FormSubLabel,
  FormSwitch,
  FormTernaryCheckBox,
  FormText,
  FormTextColors,
  FormTextSizes,
};
