import { Components } from '@metro/common';

const {
  Alert,

  Button,
  FlatList,
  Image,
  ImageBackground,
  KeyboardAvoidingView,
  Modal,
  Pressable,
  RefreshControl,
  ScrollView,
  SectionList,
  StatusBar,
  StyleSheet,
  Switch,
  Text,
  TextInput,
  TouchableHighlight,
  TouchableOpacity,
  TouchableWithoutFeedback,
  Touchable,
  View,
  VirtualizedList,
} = Components.General;

const {
  Form,
  FormArrow,
  FormCTA,
  FormCTAButton,
  FormCardSection,
  FormCheckbox,
  FormDivider,
  FormHint,
  FormIcon,
  FormInput,
  FormLabel,
  FormRadio,
  FormRow,
  FormSection,
  FormSelect,
  FormSubLabel,
  FormSwitch,
  FormTernaryCheckBox,
  FormText,
  FormTextColors,
  FormTextSizes,
} = Components.Forms;

export {
  Alert,
  Button,
  FlatList,
  Image,
  ImageBackground,
  KeyboardAvoidingView,
  Modal,
  Pressable,
  RefreshControl,
  ScrollView,
  SectionList,
  StatusBar,
  StyleSheet,
  Switch,
  Text,
  TextInput,
  TouchableHighlight,
  TouchableOpacity,
  TouchableWithoutFeedback,
  Touchable,
  View,
  VirtualizedList,

  Form,
  FormArrow,
  FormCTA,
  FormCTAButton,
  FormCardSection,
  FormCheckbox,
  FormDivider,
  FormHint,
  FormIcon,
  FormInput,
  FormLabel,
  FormRadio,
  FormRow,
  FormSection,
  FormSelect,
  FormSubLabel,
  FormSwitch,
  FormTernaryCheckBox,
  FormText,
  FormTextColors,
  FormTextSizes,
};
